apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-mf-deployment
  labels:
    name: shell-mf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shell-mf-deployment
  template:
    metadata:
      labels:
        name: shell-mf-deployment
    spec:
      containers:
        - image: shell-mf
          name: shell-mf
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
