apiVersion: skaffold/v3
kind: Config
metadata:
  name: global-store
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: global-store
      context: .
      sync:
        manual:
          - src: "src/**"
            dest: /global-store/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/cluster-ip-service.yaml
    - k8s/ingress.yaml

deploy:
  kubectl: {}
