apiVersion: v1
kind: Service
metadata:
  name: users-ms-service
  labels:
    app: users-ms-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007
  selector:
    app: users-ms-deployment
