apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mf-deployment
  labels:
    app: orders-mf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mf-deployment
  template:
    metadata:
      labels:
        app: orders-mf-deployment
    spec:
      containers:
        - name: orders-mf
          image: orders-mf
          ports:
            - containerPort: 3004
          imagePullPolicy: Never
