pipeline {
  agent {
    dockerfile {
		  filename 'frontend/dockerfile-jenkins-agent'
		}
  }
  stages {
    stage('Install dependencies') {
      steps {
        dir("frontend") {
          sh  "rm -r node_modules && npm install"
        }
      }
    }
    stage('Build') {
      steps {
        dir("frontend") {
          sh "rm -f build && npm run build"
        }
      }
    }
  }
}
