apiVersion: skaffold/v3
kind: Config
metadata:
  name: shell-mf
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: frontend-del-mf
      context: .
      sync:
        manual:
          - src: "src/**"
            dest: /frontend-del-mf/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/cluster-ip-service.yaml
    - k8s/node-port-service.yaml
    - k8s/ingress.yaml
deploy:
  kubectl: {}
