export const rows = [
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    Status: "Starting",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "DNS delegation",
    status: "Active",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    status: "Disabled",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    status: "Disabled",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    status: "Disabled",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    status: "Disabled",
    other: "Test",
    example: "",
  },
  {
    id: "load-balancer-",
    name: "Load Balancer ",
    rule: "Round robin",
    status: "Disabled",
    other: "Test",
    example: "",
  },
];
export const headers = ["Nome", "Código", "Qtde.", "Estoque Atual", "Estoque Final"];
