apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoices-db-pvc
  labels:
    app: invoices-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
