apiVersion: v1
kind: Service
metadata:
  name: shell-ms-service
  labels:
    app: shell-ms-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: shell-ms-deployment
