apiVersion: v1
kind: Service
metadata:
  name: customers-and-suppliers-db-service
  labels:
    app: customers-and-suppliers-db-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 5001
      targetPort: 5432
  selector:
    app: customers-and-suppliers-db-deployment
