apiVersion: v1
kind: PersistentVolume
metadata:
  name: customers-and-suppliers-db-volume
  labels:
    type: local
    app: customers-and-suppliers-db-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
