apiVersion: skaffold/v3
kind: Config
metadata:
  name: users-ms
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: users-ms
      context: .
      sync:
        manual:
          - src: "src/**"
            dest: /users-ms/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml
    - k8s/node-port-service.yaml
    - k8s/configmap.yaml
deploy:
  kubectl: {}
