apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms-deployment
  labels:
    app: users-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-ms-deployment
  template:
    metadata:
      labels:
        app: users-ms-deployment
    spec:
      containers:
        - image: users-ms
          name: users-ms
          ports:
            - containerPort: 4007
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: users-db-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-db-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-db-configmap
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: users-db-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: users-db-configmap
                  key: POSTGRES_PASSWORD
          imagePullPolicy: Never
