apiVersion: v1
kind: Service
metadata:
  name: orders-db-service
  labels:
    app: orders-db-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30004
      port: 5432
      name: orders-db
      targetPort: 5432
  selector:
    app: orders-db-deployment
