apiVersion: skaffold/v3
kind: Config
metadata:
  name: statistics-ms
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: statistics-ms
      context: .
      sync:
        manual:
          - src: "src/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/main.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.controller.spec.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.controller.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.module.ts"
            dest: /statistics-ms/src
            strip: "src/"

          - src: "src/**/**/**/**/**/**/**/**/*.service.ts"
            dest: /statistics-ms/src
            strip: "src/"
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/cluster-ip-service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
