apiVersion: skaffold/v3
kind: Config
metadata:
  name: users-mf
build:
  artifacts:
    - image: users-mf
      context: .
      sync:
        manual:
          - src: src/**
            dest: /users-mf/src
            strip: src/
          - src: public/**
            dest: /users-mf/public
            strip: public/
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  platforms:
    - linux/amd64
  local:
    push: false
manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml
deploy:
  kubectl: {}
