apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: patologiaclinicaunicamp.app
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shell-mf-cluster-ip-service
                port:
                  number: 3000
