apiVersion: v1
kind: Service
metadata:
  name: frontend-node-port-service
  labels:
    app: frontend-node-port-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 3000
      targetPort: 3000
  selector:
    name: frontend-cluster-ip-service
