apiVersion: skaffold/v3
kind: Config
metadata:
  name: customers-and-suppliers-mf
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: customers-and-suppliers-mf
      context: .
      sync:
        manual:
          - src: "src/**"
            dest: /customers-and-suppliers-mf/src
            strip: "src/"

      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
