### Signup a new user
POST http://localhost:4007/auth/signup
content-type: application/json

{
  "email": "saymonfelipe@hotmail.com",
  "password": "sayfel"
}

### Signin a user
POST http://localhost:4007/auth/signin
content-type: application/json

{
  "email": "saymonfelipe@hotmail.com",
  "password": "sayfel"
}

### Signout a user
POST http://localhost:4007/auth/signout
content-type: application/json


### Get the currently signed in user
GET http://localhost:4007/auth/whoami

### Delete an user
DELETE http://localhost:4007/auth/3