apiVersion: skaffold/v3
kind: Config
metadata:
  name: shell-ms
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: shell-ms
      context: .
      sync:
        manual:
          - src: "src/**"
            dest: /shell-ms/src
            strip: "src/"
manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/service.yaml
    - k8s/deployment.yaml

deploy:
  kubectl: {}
