apiVersion: skaffold/v3
kind: Config
metadata:
  name: customers-and-suppliers-db
manifests:
  rawYaml:
    - k8s/service.yaml
    - k8s/deployment.yaml
    - k8s/configmap.yaml
    - k8s/volume.yaml
    - k8s/persistent-volume-claim.yaml
deploy:
  kubectl: {}
