---
- name: Install nodejs and npm packages
  hosts: hematology_api_server
  become: true
  tasks:
    - name: Remove the old PPA if it exist
      ansible.builtin.shell:
        cmd:
          - add-apt-repository -y -r ppa:chris-lea/node.js
          - rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list
          - rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list.save
    - name: Add the NodeSource package signing key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Upgrade OS
      ansible.builtin.apt:
        upgrade: dist
    - name: Update the apt package index and install packages
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm
        force_apt_get: true
        update_cache: true
        state: build-dep