---
- name: Initial setup of Jenkins cluster instances
  hosts: jenkins_cluster
  become: true
  tasks:
    - name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        force_apt_get: true
        update_cache: true
        state: latest

    - name: Install the latest version of Docker from the official repository
      block:
        - name: Add Docker’s official GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
            state: present

        - name: Update apt and Install docker-ce
          ansible.builtin.apt:
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            force_apt_get: true
            update_cache: true
            state: latest

        - name: Add devops user to docker group
          ansible.builtin.command: usermod -aG docker $USER



