project_id              = "hematologyapp"
project_name = "HematologyApp"
server_name             = "hematology-web-server"
region                  = "southamerica-east1"
zone                    = "southamerica-east1-a"
machine_type            = "e2-micro"
ubuntu-minimal-2204-lts = "ubuntu-os-cloud/ubuntu-minimal-2204-lts"
network-subnet-cidr     = "10.158.0.0/20"
