apiVersion: v1
kind: Service
metadata:
  name: users-db-cluster-ip-service
  labels:
    app: users-db-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: users-db-deployment
