apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-ip-service
  labels:
    app: auth-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: auth-deployment
