apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mongo-credentials
          volumeMounts:
            - mountPath: /data/mongo
              name: mongodb-storage
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: auth-pvc
