apiVersion: v1
kind: Service
metadata:
  name: auth-node-port-service
  labels:
    app: auth-node-port-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 27017
      targetPort: 27017
  selector:
    app: auth-deployment
status:
  loadBalancer: {}
