apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  labels:
    app: auth-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo
