apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  storageClassName: ""
  volumeName: auth-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
