apiVersion: v1
kind: Service
metadata:
  name: supplies-mf-service
  labels:
    app: supplies-mf-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  selector:
    app: supplies-mf-deployment
